# Generated by Django 2.2.2 on 2019-06-21 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_useragecommands_userdiseasecommands'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cameratrigger',
            name='touser',
        ),
        migrations.RemoveField(
            model_name='healthsensordata',
            name='owner',
        ),
        migrations.DeleteModel(
            name='mSensorData',
        ),
        migrations.RemoveField(
            model_name='onehourelectricity',
            name='panel',
        ),
        migrations.RemoveField(
            model_name='sensordata',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='useragecommands',
            name='fromuser',
        ),
        migrations.RemoveField(
            model_name='usercommands',
            name='fromuser',
        ),
        migrations.RemoveField(
            model_name='userdiseasecommands',
            name='fromuser',
        ),
        migrations.RemoveField(
            model_name='visitors',
            name='owner',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='email',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='user',
            name='ageCategory',
        ),
        migrations.RemoveField(
            model_name='user',
            name='diseaseCategory',
        ),
        migrations.RemoveField(
            model_name='user',
            name='key',
        ),
        migrations.DeleteModel(
            name='CameraTrigger',
        ),
        migrations.DeleteModel(
            name='HealthSensorData',
        ),
        migrations.DeleteModel(
            name='OneHourElectricity',
        ),
        migrations.DeleteModel(
            name='Panel',
        ),
        migrations.DeleteModel(
            name='SensorData',
        ),
        migrations.DeleteModel(
            name='UserAgeCommands',
        ),
        migrations.DeleteModel(
            name='UserCommands',
        ),
        migrations.DeleteModel(
            name='UserDiseaseCommands',
        ),
        migrations.DeleteModel(
            name='Visitors',
        ),
    ]
