# Generated by Django 2.2.2 on 2019-06-21 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20190621_0818'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vistorName', models.CharField(max_length=100)),
                ('folderLocation', models.CharField(max_length=100)),
                ('numberPhotos', models.IntegerField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.User')),
            ],
        ),
        migrations.CreateModel(
            name='Faces',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='')),
                ('folderName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Visitors')),
            ],
        ),
    ]
