# Generated by Django 2.2.2 on 2019-06-25 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20190625_0616'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitors',
            old_name='vistorName',
            new_name='visitorName',
        ),
    ]
